name: insta_assets_picker
description: An image picker similar with Instagram, supports multi picking,
  crop and aspect ratio.
version: 1.1.1
repository: https://github.com/LeGoffMael/insta_assets_picker

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  extended_image: ^7.0.2
  flutter:
    sdk: flutter
  image_crop: ^0.4.1
  provider: ^6.0.2
  wechat_assets_picker: ^8.4.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

screenshots:
  - description: "Scroll animation"
    path: example/screenshots/scroll.webp
  - description: "Crop & export"
    path: example/screenshots/crop-export.webp
